// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WWKGameMsg.proto

package message.core;

public final class WWKGameMsgProto {
  private WWKGameMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code message.core.SysMsgType}
   */
  public enum SysMsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>JOIN = 1;</code>
     *
     * <pre>
     *加入游戏
     * </pre>
     */
    JOIN(0, 1),
    ;

    /**
     * <code>JOIN = 1;</code>
     *
     * <pre>
     *加入游戏
     * </pre>
     */
    public static final int JOIN_VALUE = 1;


    public final int getNumber() { return value; }

    public static SysMsgType valueOf(int value) {
      switch (value) {
        case 1: return JOIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SysMsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SysMsgType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SysMsgType>() {
            public SysMsgType findValueByNumber(int number) {
              return SysMsgType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return message.core.WWKGameMsgProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final SysMsgType[] VALUES = values();

    public static SysMsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private SysMsgType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:message.core.SysMsgType)
  }

  /**
   * Protobuf enum {@code message.core.GameMsgType}
   */
  public enum GameMsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SYSTEM = 1;</code>
     *
     * <pre>
     *系统
     * </pre>
     */
    SYSTEM(0, 1),
    /**
     * <code>PLAYER = 2;</code>
     *
     * <pre>
     *玩家
     * </pre>
     */
    PLAYER(1, 2),
    ;

    /**
     * <code>SYSTEM = 1;</code>
     *
     * <pre>
     *系统
     * </pre>
     */
    public static final int SYSTEM_VALUE = 1;
    /**
     * <code>PLAYER = 2;</code>
     *
     * <pre>
     *玩家
     * </pre>
     */
    public static final int PLAYER_VALUE = 2;


    public final int getNumber() { return value; }

    public static GameMsgType valueOf(int value) {
      switch (value) {
        case 1: return SYSTEM;
        case 2: return PLAYER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GameMsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameMsgType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameMsgType>() {
            public GameMsgType findValueByNumber(int number) {
              return GameMsgType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return message.core.WWKGameMsgProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final GameMsgType[] VALUES = values();

    public static GameMsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private GameMsgType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:message.core.GameMsgType)
  }

  /**
   * Protobuf enum {@code message.core.JoinerStatus}
   */
  public enum JoinerStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEAD = 1;</code>
     *
     * <pre>
     *死亡
     * </pre>
     */
    DEAD(0, 1),
    /**
     * <code>LIVE = 2;</code>
     *
     * <pre>
     *存活
     * </pre>
     */
    LIVE(1, 2),
    ;

    /**
     * <code>DEAD = 1;</code>
     *
     * <pre>
     *死亡
     * </pre>
     */
    public static final int DEAD_VALUE = 1;
    /**
     * <code>LIVE = 2;</code>
     *
     * <pre>
     *存活
     * </pre>
     */
    public static final int LIVE_VALUE = 2;


    public final int getNumber() { return value; }

    public static JoinerStatus valueOf(int value) {
      switch (value) {
        case 1: return DEAD;
        case 2: return LIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<JoinerStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<JoinerStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<JoinerStatus>() {
            public JoinerStatus findValueByNumber(int number) {
              return JoinerStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return message.core.WWKGameMsgProto.getDescriptor().getEnumTypes().get(2);
    }

    private static final JoinerStatus[] VALUES = values();

    public static JoinerStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private JoinerStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:message.core.JoinerStatus)
  }

  /**
   * Protobuf enum {@code message.core.DeadReason}
   */
  public enum DeadReason
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>KILL = 1;</code>
     *
     * <pre>
     *狼杀
     * </pre>
     */
    KILL(0, 1),
    /**
     * <code>VOTE = 2;</code>
     *
     * <pre>
     *投票
     * </pre>
     */
    VOTE(1, 2),
    /**
     * <code>POISON = 3;</code>
     *
     * <pre>
     *毒杀
     * </pre>
     */
    POISON(2, 3),
    /**
     * <code>AWAY = 4;</code>
     *
     * <pre>
     *逃跑
     * </pre>
     */
    AWAY(3, 4),
    ;

    /**
     * <code>KILL = 1;</code>
     *
     * <pre>
     *狼杀
     * </pre>
     */
    public static final int KILL_VALUE = 1;
    /**
     * <code>VOTE = 2;</code>
     *
     * <pre>
     *投票
     * </pre>
     */
    public static final int VOTE_VALUE = 2;
    /**
     * <code>POISON = 3;</code>
     *
     * <pre>
     *毒杀
     * </pre>
     */
    public static final int POISON_VALUE = 3;
    /**
     * <code>AWAY = 4;</code>
     *
     * <pre>
     *逃跑
     * </pre>
     */
    public static final int AWAY_VALUE = 4;


    public final int getNumber() { return value; }

    public static DeadReason valueOf(int value) {
      switch (value) {
        case 1: return KILL;
        case 2: return VOTE;
        case 3: return POISON;
        case 4: return AWAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DeadReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DeadReason>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeadReason>() {
            public DeadReason findValueByNumber(int number) {
              return DeadReason.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return message.core.WWKGameMsgProto.getDescriptor().getEnumTypes().get(3);
    }

    private static final DeadReason[] VALUES = values();

    public static DeadReason valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DeadReason(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:message.core.DeadReason)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020WWKGameMsg.proto\022\014message.core*\026\n\nSysM" +
      "sgType\022\010\n\004JOIN\020\001*%\n\013GameMsgType\022\n\n\006SYSTE" +
      "M\020\001\022\n\n\006PLAYER\020\002*\"\n\014JoinerStatus\022\010\n\004DEAD\020" +
      "\001\022\010\n\004LIVE\020\002*6\n\nDeadReason\022\010\n\004KILL\020\001\022\010\n\004V" +
      "OTE\020\002\022\n\n\006POISON\020\003\022\010\n\004AWAY\020\004B\021B\017WWKGameMs" +
      "gProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
